# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b38173e3c9827eb328cae5139b54951eb717ae55ef6744783e909fe2e9cd62a11a3a526d48892c62e3c73592745108b8a2dc625a55a2f31a095559ee116d8ab6

test:
  secret_key_base: 7be588e3d4a1541548be3fb39cd9c5b2d5090edb2ee9f37b9f1d5ce1fb954b772602fb40b4583425b947ee1cfa34c0fe39885049804066583ad6377d84540ec2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
